### PR TITLE
Merge wrapper modules and reorganize build script

### LINKED ISSUE #45: Merge minecraft and QSL modules
#35 should be merged first

### PR DESCRIPTION
**Pull request by Cypher121**
Simplifies the project layout into root project (now also building the fatjar), core (stdlib, reflect, and adapter), and library (everything else.

Still room for some buildscript changes like only running dokka on the library subproject.

Closes #45

### CODE REVIEW

**Comment by SilverAndro** [comment]
Looks good

Has this been tested to make sure everything is remapped properly?

**Comment by Cypher121** [comment]
So far only to the point of it building and publishing to local properly, any tests in particular I should do?

**Comment by SilverAndro** [comment]
Iirc the big issue was receivers in the QSL wrappers didn't get remapped, so pulling it locally and checking that would be what I do

**Comment by Cypher121** [comment]
Did some testing (and this time actually adding QKL as `modImplementation`): both functions with receivers (tested on `ServerWorld.playersInWorld`) and typealiases (tested on `BlockTest`) remap properly, as do normal references.

**Comment by SilverAndro** [comment]
Alright nice

**Review by SilverAndro — APPROVED** [review]

**Review by Oliver-makes-code — APPROVED** [review]
LGTM

**Review by NoComment1105 — APPROVED** [review]
LGTM 👍🏼

**Review by PotatoPresident — APPROVED** [review]

**Comment by SilverAndro** [comment]
🎉

**Pull request merged**
