### PR TITLE
Update to 1.20.2

### PR DESCRIPTION
**Pull request by ellie-semele**
Sorry for having this deleted before, original PR message below:
> Been told https://github.com/QuiltMC/quilt-kotlin-libraries/pull/84 is urgent to merge otherwise built artifacts would be broken otherwise.
>
>At the moment I've only updated versions to track with the latest FLK and get it to compile with `1.20.2`. There are some other changes which should likely be addressed before this gets merged:
> 
>- [x] The annotation `@CodecSerializable.Polymorphic` is not top level, `@MetaSerializable` used to allow this however it's now been deprecated and it only supports top level annotations.
>- [x] There has been networking refactors and I or someone else probably need to add more extensions for those.
>- [x] Parts of the code base is generated with Silver's math codegen project, those haven't been looked at but may need some updating.
>- [x] Fabric Language Kotlin's language adapter seems to have broken due to changes in Kotlin 1.9.20, should verify our language adapter still works: [Changes for upstream since last bump](https://github.com/FabricMC/fabric-language-kotlin/compare/2c8819...HEAD)
>- [x] Switch to using Yumi Licenser

### CODE REVIEW

**Comment by ellie-semele** [comment]
I'll try and recap the other messages I sent, but I didn't save them like the original:
1. It seems like math types haven't changed between 1.20.1 and 1.20.2
2. Some of the methods have been renamed to match QSL, therefore API breakage, also fixed a deprecation with the annotation mentioned not being top level which is another breaking change.
3. Fixed licenser not working on java files in addition to switching to yumi-licenser.
4. Found out object function entry points didn't work when testing the language adapter so fixed that as well.

**Review by sschr15 — APPROVED** [review]
Looks good, just want a quick confirmation that it can be merged as well as that the codec changes didn't accidentally break things, as that looks like it's probably the most fragile

**Comment by ellie-semele** [comment]
I was unaware of any Codec changes tbh, I assume any tests would have ran and passed, Codecs otherwise aren't in my area of expertise, if there's any notable mod I can test with real quick I'll give that a shot.

**Comment by ellie-semele** [comment]
Sadly it appears there are Codec issues in the samples I didn't spot before. Will try and take a look at those now.

**Comment by ellie-semele** [comment]
Managed to hack something together to run the Codec serialization tests and they all pass.

```
[17:54:24] [Render thread/INFO] (Minecraft) [STDOUT]: Running samples.qkl.serialization.BasicSerializationTests:testBasicDecoding    
[17:54:24] [Render thread/INFO] (Minecraft) [STDOUT]: Running samples.qkl.serialization.BasicSerializationTests:testBasicEncoding    
[17:54:24] [Render thread/INFO] (Minecraft) [STDOUT]: Running samples.qkl.serialization.NullableSerializationTests:testAmbiguousInlineNullsUnwrapped    
[17:54:24] [Render thread/INFO] (Minecraft) [STDOUT]: Running samples.qkl.serialization.NullableSerializationTests:testAmbiguousInlineNullsWrapped    
[17:54:24] [Render thread/INFO] (Minecraft) [STDOUT]: Running samples.qkl.serialization.NullableSerializationTests:testBasicNullableValue    
[17:54:24] [Render thread/INFO] (Minecraft) [STDOUT]: DataResult[Left[null]]
[17:54:24] [Render thread/INFO] (Minecraft) [STDOUT]: Running samples.qkl.serialization.NullableSerializationTests:testExplicitNullFields    
[17:54:24] [Render thread/INFO] (Minecraft) [STDOUT]: Running samples.qkl.serialization.NullableSerializationTests:testImplicitNullFields    
[17:54:24] [Render thread/INFO] (Minecraft) [STDOUT]: Running samples.qkl.serialization.PolymorphicSerializationTests:testConflictingDiscriminator    
[17:54:24] [Render thread/INFO] (Minecraft) [STDOUT]: Running samples.qkl.serialization.PolymorphicSerializationTests:testFlattenedDecoding    
[17:54:24] [Render thread/INFO] (Minecraft) [STDOUT]: Running samples.qkl.serialization.PolymorphicSerializationTests:testFlattenedEncoding    
[17:54:24] [Render thread/INFO] (Minecraft) [STDOUT]: Running samples.qkl.serialization.PolymorphicSerializationTests:testStructuredDecoding    
[17:54:24] [Render thread/INFO] (Minecraft) [STDOUT]: Running samples.qkl.serialization.PolymorphicSerializationTests:testStructuredEncoding    
[17:54:25] [Render thread/INFO] (Minecraft) [STDOUT]: Running samples.qkl.serialization.MapSerializationTests:testAllowedMapDecoding    
[17:54:25] [Render thread/INFO] (Minecraft) [STDOUT]: DataResult[Left[({AllowedCodecInline(field=foo:bar)=baz}, null)]]
[17:54:25] [Render thread/INFO] (Minecraft) [STDOUT]: Running samples.qkl.serialization.MapSerializationTests:testAllowedMapEncoding    
[17:54:25] [Render thread/INFO] (Minecraft) [STDOUT]: Running samples.qkl.serialization.MapSerializationTests:testInvalidMapEncoding    
[17:54:25] [Render thread/INFO] (Minecraft) [STDOUT]: All tests succeeded```

**Pull request merged**
