### PR TITLE
Implement fatjar as a submodule

### PR DESCRIPTION
**Pull request by Oliver-makes-code**

### CODE REVIEW

**Comment by wafflecoffee** [comment]
This probably can just be a task instead of a subproject

**Comment by Oliver-makes-code** [comment]
> This probably can just be a task instead of a subproject

How would I go about doing that?

**Review by NoComment1105 — APPROVED** [review]

**Review by PotatoPresident — APPROVED** [review]

**Comment by SilverAndro** [comment]
Im a bit confused why this is needed tbh, shouldn't loom handle this for us?

Or if not couldn't we just pull in the shadow plugin?

**Comment by Oliver-makes-code** [comment]
> Im a bit confused why this is needed tbh, shouldn't loom handle this for us?
We use `include` to JiJ the modules

> Or if not couldn't we just pull in the shadow plugin?
The QMJs won't carry over

**Comment by SilverAndro** [comment]
Hm, fair enough I suppose

**Review by SilverAndro — APPROVED** [review]

**Pull request merged**
