### PR TITLE
Update to 1.20.4

### PR DESCRIPTION
**Pull request by SylvKT**

### CODE REVIEW

**Review by sschr15 — APPROVED** [review]
Cool, if it builds and runs, I could merge

**Comment by SylvKT** [comment]
built, game runs (tested on local machine)

**Comment by SylvKT** [comment]
Last minute question, should this be 4.0.0?

**Comment by quinn-semele** [comment]
Btw I bumped the major since the API surface had a breaking change, this is kind of just an issue with modding minecraft, each minor and likely patch versions will cause breakage. I guess this can be thought more as "should mods be using semver when Minecraft doesn't"

**Pull request merged**
