### PR TITLE
1.19.2 + dependencies update

### LINKED ISSUE #42: Bump target version to 1.19.2 (and all deps)

### PR DESCRIPTION
**Pull request by SilverAndro**
Closes #42, also removes some warnings

### CODE REVIEW

**Review by Oliver-makes-code — APPROVED** [review]

**Review by Cypher121 — APPROVED** [review]

**Review by NoComment1105 — APPROVED** [review]

**Comment by solonovamax** [comment]
[quilt.mod.json](https://github.com/QuiltMC/quilt-kotlin-libraries/blob/main/core/src/main/resources/quilt.mod.json#L31) needs to be updated to provide version `1.8.3+kotlin.1.7.10` of `fabric-language-kotlin`. (Perhaps this should be done automatically through the `processResources` task in the buildscript, to make it easier?)

**Comment by SilverAndro** [comment]
will do!

Personally id prefer not to automate it so that we can properly bump the version number when required, if any breaking changes appear

**Comment by solonovamax** [comment]
> Personally id prefer not to automate it so that we can properly bump the version number when required, if any breaking changes appear

I just feel it should be automated, because currently it's defined in several places.

Here's what I'd recommend:

`libs.versions.toml`
```toml
[versions]
flk = "1.8.2"
```
`build.gradle.kts`:
```kotlin
val kotlinVersion = project.libs.versions.kotlin.orNull
val flkVersion = project.libs.versions.flk.orNull
version = "$rootVersion+kt.$kotlinVersion+flk.${flkVersion}"

/* ... */

tasks {
    processResources {
        inputs.properties(
                "version" to rootVersion,
                "flkVersion" to flkVersion,
                "kotlinVersion" to kotlinVersion,
                         )
        filesMatching("quilt.mod.json") {
            expand(
                    "version" to rootVersion,
                    "flkVersion" to flkVersion,
                    "kotlinVersion" to kotlinVersion,
                  )
        }
    }
}
```
`quilt.mod.json`:
```json
{
  "schema_version": 1,
  "quilt_loader": {
    "group": "org.quiltmc.qkl",
    "id": "qkl_core",
    "version": "${version}",
    // ...
    "provides": [
      {
        "id": "fabric-language-kotlin",
        "version": "${flkVersion}+kotlin.${kotlinVersion}"
      }
    ],
    // ...
  },
  // ...
}
```

This way, you only need to change the values in `libs.versions.toml`, and all the relevant versions will be updated. Alternatively, since the "Fabric Language Kotlin version" is kind of a project property (and not a dependency), it might be better to be defined in `gradle.properties`.

**Comment by SilverAndro** [comment]
Your solution doesnt handle bumping the version automatically on breaking changes though, so the benefit is overall incredibly minimal as everything still needs to be checked manually

**Review by PotatoPresident — APPROVED** [review]

**Comment by solonovamax** [comment]
> Your solution doesnt handle bumping the version automatically on breaking changes though, so the benefit is overall incredibly minimal as everything still needs to be checked manually

Well yeah. Obviously, everything needs to be checked manually. The same applies to any time that [this line](https://github.com/QuiltMC/quilt-kotlin-libraries/blob/main/build.gradle.kts#L33) is updated. It does however remove the need to update the fabric language kotlin version *twice*. Once in `build.gradle.kts` and a second time in `quilt.mod.json`.

**Comment by SilverAndro** [comment]
Fair, ill look into it when the next update rolls around

**Pull request merged**
