### PR TITLE
Fix remapping by making included modules be `namedElements`

### PR DESCRIPTION
**Pull request by SilverAndro**
Tested locally and seems to work

Thanks to @jakobkmar for providing the fix for this on discord

### CODE REVIEW

**Review by Oliver-makes-code — CHANGES_REQUESTED** [review]
The `includeApi` function can be safely removed now that it's unused

**Comment by SilverAndro** [comment]
Missed that that was user defined, ive repurposed it

**Comment by SilverAndro** [comment]
Well this seem to breaking due to some change in https://github.com/QuiltMC/quilt-loom/blob/main/patches/0002-Support-multiple-metadata-formats-including-QMJ.patch, so guess ill investigate that

**Comment by SilverAndro** [comment]
Welp this has spiraled due to awful loom design, we'll likely have to rewrite the entire buildscript system to fix this

**Pull request closed without merging**
