### PR TITLE
Sync with FLK 1.10.18, Update some plugin versions.

### PR DESCRIPTION
**Pull request by quinn-semele**
Nothing seems to have broken plugin wise so I think this is it...

### CODE REVIEW

**Comment by SylvKT** [comment]
is it okay if i use this PR as a base for updating to 1.20.4? I saw someone else tried to update, but their account has since been deleted.

**Comment by quinn-semele** [comment]
Honestly, if your up to doing that then sure, I'm kind of just bored with the waiting so...

Also that was my account, if you want the code from that to also act as a base I can upload it to github again.

**Comment by SylvKT** [comment]
> Also that was my account, if you want the code from that to also act as a base I can upload it to github again.

@quinn-semele Could you upload it again please? Thanks :3

**Comment by quinn-semele** [comment]
Yeah sure, here you go: https://github.com/quinn-semele/quilt-kotlin-libraries/tree/1.20.4, haven't checked for newer changes so might be a little work left still.

**Comment by quinn-semele** [comment]
Closing as another is going to take over this PR.

**Pull request closed without merging**
