### PR TITLE
Add binary compatibility validator

### LINKED ISSUE #41: Look into using https://github.com/Kotlin/binary-compatibility-validator
[Clickable version](https://github.com/Kotlin/binary-compatibility-validator)

### PR DESCRIPTION
**Pull request by SilverAndro**
Closes #41 

Kotlin's binary compatibility validator plugin means that we can make committing fail if changes have been made to the public ABI.

To check for changes to the public abi, just run the `apiCheck` task, and it will fail if so and tell you exactly what changed, and if the change is intentional, you can run `apiDump` to update the api file (and then bump the version manually). The check task is also setup to run on commit. ABI checking is also excluded from `core` and `fatjar` as those do not provide an ABI surface for end users.
 
I didnt add this to actions, but it probably should be if anyone knows how to do that?

### CODE REVIEW

**Comment by SilverAndro** [comment]
Actually never mind on actions, the plugin seems to inject itself into `build`, making it run automatically

**Review by PotatoPresident — APPROVED** [review]

**Comment by Oliver-makes-code** [comment]
I don't quite like the idea of using this plugin, as it would block us into supporting APIs that break badly between Minecraft versions

**Comment by Cypher121** [comment]
If an ABI break is expected/unavoidable/desired, simply running `gradle apiDump` before committing will make the plugin not give errors, as it will now compare against the new dump.

The only thing this prevents is *accidental* changes to the ABI by making them more noticeable as line deletions in api files.

Besides that, every new feature PR should `apiDump` regardless to add the new methods to the files.

**Comment by Cypher121** [comment]
Basically, the order should be `apiCheck apiDump` or `build apiDump` to make sure you're only adding, and if you have a good reason to remove/change, then just rune `apiDump` by itself and you're set.

**Comment by Oliver-makes-code** [comment]
I guess that's fine then

**Review by Oliver-makes-code — APPROVED** [review]

**Comment by SilverAndro** [comment]
Yeah the main idea is for people to be aware "this change is an abi break"

On my machine updating the api files only takes about 5 seconds so its not a major issue, and it doesnt block adding, only changes, so new apis dont need to run it before every test

**Review by NoComment1105 — APPROVED** [review]

**Comment by NoComment1105** [comment]
This has merge conflicts, and is due for merge, please fix them and then it can be merged immediately

**Comment by SilverAndro** [comment]
I don't have a laptop atm, if anyone else could update this that would be great

**Pull request merged**
