### PR TITLE
Sync with FLK 1.12.3, target MC 1.21

### PR DESCRIPTION
**Pull request by quinn-semele**
Superscedes https://github.com/QuiltMC/quilt-kotlin-libraries/pull/98, original PR message will be embeded below...
- Syncs with FLK 1.12.3 by embedding it.
- Updates to QSL 1.21.1.
- Removes the language adapter in favour of FLK's.
- Applies the later suggestions by 770grappenmaker
- Updates the gradle wrapper to latest (8.10.2).
- Bumps the major version due to api surface breakage.

> Main highlights :
> - item tooltip API now takes a DataComponentMap argument instead of an NbtCompound
> - some Brigadier DSL methods now take an additional context parameter 
>   - future refactors of the DSL could hide this parameter away inside a receiver object
> - some Brigadier classes are still unmapped
> Fixes https://github.com/QuiltMC/quilt-kotlin-libraries/issues/96 and https://github.com/QuiltMC/quilt-kotlin-libraries/issues/97

### CODE REVIEW

**Review by OroArmor — APPROVED** [review]

**Review by TheEpicBlock — APPROVED** [review]

**Comment by quinn-semele** [comment]
Requires testing of the bundling of FLK I did but otherwise should be good to go.

**Review by OroArmor — APPROVED** [review]
Looks like you are defaulting to FLK for the language provider and just keeping the api?

**Comment by quinn-semele** [comment]
Yeah that's the plan going forward, core would effectively be gone unless we want to bundle more libraries in the future.

**Comment by quinn-semele** [comment]
I believe this PR is ready to be merged, please also see and maybe adjust a little https://discord.com/channels/817576132726620200/1103987526349361192/1294387464848408757.

**Pull request merged**
