### PR TITLE
1.19.4 update

### PR DESCRIPTION
**Pull request by SilverAndro**
We gaming

This would be 2.0.0 due to the API breakage

### CODE REVIEW

**Review by Oliver-makes-code — APPROVED** [review]
LGTM

**Review by Oliver-makes-code — APPROVED** [review]
mfw re-requested lmao

**Review by sschr15 — COMMENTED** [review]
Just one small naming convention thing

**Review by sschr15 — APPROVED** [review]

**Review by PotatoPresident — APPROVED** [review]
2.0 here we come

**Review by NoComment1105 — APPROVED** [review]
LGTM

**Review by Earthcomputer — APPROVED** [review]

**Pull request merged**
